name: AWS Lambda Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda-batch
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: lambda update
        run: |
          cd ./lambda_src && npm ci
          zip -r package.zip ./*
          aws lambda update-function-code --function-name sample-lambda-batch --environment Variables="{"lineApiToken"=${{ secrets.LINE_API_TOKEN }}, "slackBotToken"=${{ secrets.SLACK_BOT_TOKEN }}, "webHookUrl"=${{ secrets.SLACK_WEBHOOK_URL}}, "slackBotToken"=${{ secrets.SLACK_BOT_TOKEN }}, "lineApiUrl"=${{ secrets.LINE_API_URL }}, "threshold"="${{ secrets.THRESHOULD }}}" --zip-file fileb://package.zip --publish
 


